services:
  databaseservice:
    image: databaseservice
    build:
      context: .
      dockerfile: DatabaseService/Dockerfile
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: notifier
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: pass123
    ports:
      - "5672:5672"  # порт для AMQP (основной протокол RabbitMQ)
      - "15672:15672" # порт для управления через браузер
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
    driver: bridge
